name: Auto Assign

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Assign Reviewers and Assignees
        uses: kentaro-m/auto-assign-action@v1.2.2
        with:
          addReviewers: true
          addAssignees: author
          reviewers: |
            WazedKhan
            WazedKhan-Repliq
          numberOfReviewers: 1
          numberOfAssignees: 0
          skipKeywords: |
            wip
            draft
